projects:
  database:
    schemaPath: /Users/kevan/Documents/projects/meagn_stack/server/src/database/prisma.graphql
    extensions:
      prisma: /Users/kevan/Documents/projects/meagn_stack/server/src/database/prisma.yml
  app:
    schemaPath: src/graphql/types/rootTypes.js
    extensions: 
      endpoints:
        default: http://localhost:4000